"""
Intent Training Dataset for Ensemble NLP Classifier
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
500+ labeled examples covering 8 intent categories.
Used to train the TF-IDF + SVM classifier and build
the Semantic Embedding anchor index.

Each entry: (query_text, intent_label)
"""

TRAINING_DATA = [
    # ═══════════════════════════════════════════════════════════
    # SALES_QUERY — Revenue, earnings, order counts, AOV, trends
    # ═══════════════════════════════════════════════════════════
    ("What are today's sales?", "sales_query"),
    ("How much revenue did we make today?", "sales_query"),
    ("Show me today's earnings", "sales_query"),
    ("Total income for today", "sales_query"),
    ("How many orders did we get today?", "sales_query"),
    ("What's our revenue this week?", "sales_query"),
    ("How much did we earn yesterday?", "sales_query"),
    ("Show me this month's sales", "sales_query"),
    ("Compare this week vs last week sales", "sales_query"),
    ("What's the sales trend for the last 7 days?", "sales_query"),
    ("How much money did we make?", "sales_query"),
    ("What was last week's revenue?", "sales_query"),
    ("Give me the monthly revenue report", "sales_query"),
    ("How are sales today compared to yesterday?", "sales_query"),
    ("Show total revenue for the last 30 days", "sales_query"),
    ("What's the average order value?", "sales_query"),
    ("AOV for this week?", "sales_query"),
    ("What's our best selling day?", "sales_query"),
    ("How many orders came in today?", "sales_query"),
    ("What are the peak hours for sales?", "sales_query"),
    ("Peak hour analysis for this week", "sales_query"),
    ("When do we get the most orders?", "sales_query"),
    ("Show me the daily sales trend", "sales_query"),
    ("Revenue growth this month", "sales_query"),
    ("Are sales going up or down?", "sales_query"),
    ("How much cash did we pull in today?", "sales_query"),
    ("Total takings for the day", "sales_query"),
    ("What's our daily average revenue?", "sales_query"),
    ("Give me a sales breakdown by day", "sales_query"),
    ("How are we doing this week in terms of revenue?", "sales_query"),
    ("Sales performance for this month", "sales_query"),
    ("How's business today?", "sales_query"),
    ("What was our best day this week?", "sales_query"),
    ("Show me the order count trend", "sales_query"),
    ("What did we make last month?", "sales_query"),
    ("How is revenue trending?", "sales_query"),
    ("Compare dine-in vs takeaway sales", "sales_query"),
    ("What's the total billing amount today?", "sales_query"),
    ("Show me the forecast for next week", "sales_query"),
    ("Predict next week's revenue", "sales_query"),
    ("Revenue forecast", "sales_query"),
    ("Sales forecast for the upcoming days", "sales_query"),
    ("What's our projected income?", "sales_query"),
    ("Weekly performance summary", "sales_query"),
    ("Are we hitting our sales targets?", "sales_query"),
    ("How much UPI payments came in today?", "sales_query"),
    ("Payment breakdown by mode", "sales_query"),
    ("Cash vs UPI vs card payments today", "sales_query"),
    ("How many dine-in orders today?", "sales_query"),
    ("Takeaway vs dine-in order count", "sales_query"),
    ("What is today's total?", "sales_query"),
    ("Aaj ka total kitna hua?", "sales_query"),
    ("Kitne orders aaye aaj?", "sales_query"),
    ("Profit kya hai aaj ka?", "sales_query"),
    ("Revenue kitna hai is week ka?", "sales_query"),
    ("What's the top selling item today?", "sales_query"),
    ("Best seller this week?", "sales_query"),
    ("Which item sold the most?", "sales_query"),
    ("Top 5 selling items", "sales_query"),
    ("Show top 5 selling items", "sales_query"),
    ("Show me the top 5 selling items", "sales_query"),
    ("Show top 10 selling items", "sales_query"),
    ("What are the top selling items?", "sales_query"),
    ("List top selling dishes", "sales_query"),
    ("Top selling items this week", "sales_query"),
    ("Top selling items this month", "sales_query"),
    ("Top selling items today", "sales_query"),
    ("Show me best selling items", "sales_query"),
    ("What are our top sellers?", "sales_query"),
    ("Which items are selling the most?", "sales_query"),
    ("Best selling dishes this week", "sales_query"),
    ("Top 3 items by sales", "sales_query"),
    ("Most popular items this week", "sales_query"),
    ("Most popular dishes this month", "sales_query"),
    ("Which dish is flying off the shelves?", "sales_query"),
    ("What are customers ordering the most?", "sales_query"),
    ("Item-wise sales breakdown", "sales_query"),
    ("Which item has highest sales?", "sales_query"),
    ("Rank items by number of orders", "sales_query"),

    # ═══════════════════════════════════════════════════════════
    # INVENTORY_QUERY — Stock, ingredients, low stock, expiry
    # ═══════════════════════════════════════════════════════════
    ("What's the current stock level?", "inventory_query"),
    ("Show me low stock items", "inventory_query"),
    ("Which ingredients are running low?", "inventory_query"),
    ("Do we have enough cheese?", "inventory_query"),
    ("How much paneer do we have?", "inventory_query"),
    ("Check tomato stock", "inventory_query"),
    ("Are any items about to run out?", "inventory_query"),
    ("Which items need reordering?", "inventory_query"),
    ("Show me reorder alerts", "inventory_query"),
    ("Inventory status", "inventory_query"),
    ("What's expiring soon?", "inventory_query"),
    ("Show expired items", "inventory_query"),
    ("Which ingredients have expired?", "inventory_query"),
    ("Expiry date check", "inventory_query"),
    ("Are there any expired items in stock?", "inventory_query"),
    ("Show me items expiring this week", "inventory_query"),
    ("What items are about to expire?", "inventory_query"),
    ("Shelf life check for all items", "inventory_query"),
    ("Which items need to be used first?", "inventory_query"),
    ("How many days until chicken expires?", "inventory_query"),
    ("Show me expiry alerts", "inventory_query"),
    ("What's the expiry risk value?", "inventory_query"),
    ("How much stock is at risk of expiring?", "inventory_query"),
    ("Ingredient availability check", "inventory_query"),
    ("Do we have enough oil for today?", "inventory_query"),
    ("How much rice is left?", "inventory_query"),
    ("Stock check for onions", "inventory_query"),
    ("Is butter chicken makeable right now?", "inventory_query"),
    ("Can we make 50 burgers with current stock?", "inventory_query"),
    ("How many servings of pizza can we make?", "inventory_query"),
    ("List all ingredients below reorder level", "inventory_query"),
    ("Which items should I order from supplier?", "inventory_query"),
    ("Kaunsa item khatam hone wala hai?", "inventory_query"),
    ("Stock kitna bacha hai?", "inventory_query"),
    ("Paneer kitna hai abhi?", "inventory_query"),
    ("Kya cheese hai stock mein?", "inventory_query"),
    ("Expiry date dikahao", "inventory_query"),
    ("What raw materials are we short on?", "inventory_query"),
    ("Ingredient report", "inventory_query"),
    ("Show me the full inventory list", "inventory_query"),

    # ═══════════════════════════════════════════════════════════
    # ORDER_STATUS — Track orders, pending, KOT, active orders
    # ═══════════════════════════════════════════════════════════
    ("Show me pending orders", "order_status"),
    ("What orders are currently active?", "order_status"),
    ("Is order ORD-20240315-0042 ready?", "order_status"),
    ("Check status of order 42", "order_status"),
    ("How many orders are in the kitchen?", "order_status"),
    ("Show me orders being prepared", "order_status"),
    ("Are there any orders waiting?", "order_status"),
    ("What's cooking right now?", "order_status"),
    ("Kitchen order status", "order_status"),
    ("KOT status update", "order_status"),
    ("How many orders are pending?", "order_status"),
    ("Show me all active orders", "order_status"),
    ("List orders that haven't been served yet", "order_status"),
    ("Which tables are waiting for food?", "order_status"),
    ("Any delayed orders?", "order_status"),
    ("Show me the order queue", "order_status"),
    ("What's the status of table 5's order?", "order_status"),
    ("Is the food ready for table 3?", "order_status"),
    ("How long has order 15 been waiting?", "order_status"),
    ("Track my last order", "order_status"),
    ("Show orders placed in the last hour", "order_status"),
    ("Pending KOTs in kitchen", "order_status"),
    ("Kitne orders pending hai?", "order_status"),
    ("Table 4 ka order kaha tak aaya?", "order_status"),
    ("Kitchen mein kya chal raha hai?", "order_status"),
    ("Any cancelled orders today?", "order_status"),
    ("Show me completed orders today", "order_status"),

    # ═══════════════════════════════════════════════════════════
    # MENU_INFO — Prices, availability, menu details
    # ═══════════════════════════════════════════════════════════
    ("What's on the menu?", "menu_info"),
    ("Show me the full menu", "menu_info"),
    ("How much does a burger cost?", "menu_info"),
    ("What's the price of butter chicken?", "menu_info"),
    ("Is pizza available right now?", "menu_info"),
    ("Show me all available items", "menu_info"),
    ("List items in the appetizers category", "menu_info"),
    ("What desserts do we have?", "menu_info"),
    ("Price list for all items", "menu_info"),
    ("How many items are on the menu?", "menu_info"),
    ("What items are unavailable?", "menu_info"),
    ("Show me the drinks menu", "menu_info"),
    ("Cost of a masala dosa", "menu_info"),
    ("What's the cheapest item?", "menu_info"),
    ("What's our most expensive dish?", "menu_info"),
    ("Menu items under 200 rupees", "menu_info"),
    ("List all main course items", "menu_info"),
    ("What's in the starters section?", "menu_info"),
    ("Burger ka price kya hai?", "menu_info"),
    ("Menu dikahao", "menu_info"),
    ("Kya available hai abhi?", "menu_info"),
    ("Pizza ki price bata do", "menu_info"),
    ("Show veg items only", "menu_info"),
    ("What are the non-veg options?", "menu_info"),
    ("Any new items on the menu?", "menu_info"),

    # ═══════════════════════════════════════════════════════════
    # WASTAGE_QUERY — Waste logs, spoilage, food waste tracking
    # ═══════════════════════════════════════════════════════════
    ("How much wastage this week?", "wastage_query"),
    ("Show me wastage report", "wastage_query"),
    ("What was wasted today?", "wastage_query"),
    ("Total wastage cost this month", "wastage_query"),
    ("Which items had the most wastage?", "wastage_query"),
    ("Wastage analysis for the last 7 days", "wastage_query"),
    ("How much food was thrown away?", "wastage_query"),
    ("Spoilage report", "wastage_query"),
    ("What ingredients were damaged?", "wastage_query"),
    ("Kitchen waste this week", "wastage_query"),
    ("How much did we lose to wastage?", "wastage_query"),
    ("Wastage cost breakdown", "wastage_query"),
    ("Show me wastage trends", "wastage_query"),
    ("Is wastage increasing or decreasing?", "wastage_query"),
    ("Top wastage items this month", "wastage_query"),
    ("How much expired food was thrown out?", "wastage_query"),
    ("Wastage report for yesterday", "wastage_query"),
    ("What's the total spoilage cost?", "wastage_query"),
    ("Kitna waste hua is week?", "wastage_query"),
    ("Kaunsa item sabse zyada waste hota hai?", "wastage_query"),

    # ═══════════════════════════════════════════════════════════
    # REVENUE_INTEL — Margins, profitability, BCG, combos, upsells
    # ═══════════════════════════════════════════════════════════
    ("What are our highest margin items?", "revenue_intel"),
    ("Show me profit margins for all items", "revenue_intel"),
    ("Which items have the best profitability?", "revenue_intel"),
    ("Food cost percentage analysis", "revenue_intel"),
    ("Give me a margin report", "revenue_intel"),
    ("Which items are most profitable?", "revenue_intel"),
    ("Show me the BCG matrix for menu items", "revenue_intel"),
    ("What are our star items?", "revenue_intel"),
    ("Which items are workhorses?", "revenue_intel"),
    ("Show me puzzle items on the menu", "revenue_intel"),
    ("What are our dog items that should be removed?", "revenue_intel"),
    ("Sales velocity analysis", "revenue_intel"),
    ("Item popularity ranking", "revenue_intel"),
    ("Which combos should we promote?", "revenue_intel"),
    ("Suggest combo deals", "revenue_intel"),
    ("What items are frequently ordered together?", "revenue_intel"),
    ("Association analysis for combos", "revenue_intel"),
    ("Give me upselling suggestions", "revenue_intel"),
    ("What should we upsell?", "revenue_intel"),
    ("Upsell recommendations", "revenue_intel"),
    ("Smart upselling opportunities", "revenue_intel"),
    ("Price optimization suggestions", "revenue_intel"),
    ("Which items should we reprice?", "revenue_intel"),
    ("Should we increase or decrease any prices?", "revenue_intel"),
    ("Pricing recommendations", "revenue_intel"),
    ("What are our hidden gems?", "revenue_intel"),
    ("Under-promoted high margin items", "revenue_intel"),
    ("Which good items are we not selling enough of?", "revenue_intel"),
    ("Low margin risk items", "revenue_intel"),
    ("Which items are eroding our profits?", "revenue_intel"),
    ("Full revenue intelligence report", "revenue_intel"),
    ("Give me the complete menu analysis", "revenue_intel"),
    ("Revenue intelligence dashboard data", "revenue_intel"),
    ("How can we increase profits?", "revenue_intel"),
    ("Suggest ways to improve profitability", "revenue_intel"),
    ("What changes should we make to improve margins?", "revenue_intel"),
    ("Contribution margin analysis", "revenue_intel"),
    ("Item-level profitability breakdown", "revenue_intel"),
    ("Which items give us the highest profit per unit?", "revenue_intel"),
    ("Menu engineering analysis", "revenue_intel"),
    ("Inventory-linked performance signals", "revenue_intel"),
    ("Which profitable items are at stock risk?", "revenue_intel"),
    ("Kaunsa item sabse zyada profitable hai?", "revenue_intel"),
    ("Combo suggest karo", "revenue_intel"),
    ("Margin kya hai har item ka?", "revenue_intel"),

    # ═══════════════════════════════════════════════════════════
    # CREATE_ORDER — Placing orders, adding items
    # ═══════════════════════════════════════════════════════════
    ("Add 2 burgers to table 5", "create_order"),
    ("Place an order for 3 pizzas", "create_order"),
    ("I want to order 1 butter chicken and 2 naan", "create_order"),
    ("Order 2 masala dosa for takeaway", "create_order"),
    ("Add 1 coke and 1 sprite to table 3", "create_order"),
    ("Get me 2 biryani", "create_order"),
    ("Place order: 1 paneer tikka, 2 garlic naan", "create_order"),
    ("Order 5 samosas for table 1", "create_order"),
    ("I need 3 coffees", "create_order"),
    ("Add chicken wings to the order", "create_order"),
    ("Table 7 wants 2 thali and 3 lassi", "create_order"),
    ("Takeaway: 2 wraps and 1 fries", "create_order"),
    ("New order for 1 pasta and 1 mojito", "create_order"),
    ("Order chahiye: 2 burger aur 1 coke", "create_order"),
    ("Table 4 ko 3 pizza bhejo", "create_order"),
    ("Delivery order: 1 biryani, 1 raita", "create_order"),
    ("Ek butter chicken dal do order mein", "create_order"),
    ("Create order for walk-in customer", "create_order"),
    ("Ring up 2 sandwiches and a juice", "create_order"),
    ("Punch in an order for table 10", "create_order"),

    # ═══════════════════════════════════════════════════════════
    # UPDATE_MENU_ITEM — Change price, toggle availability, update details
    # ═══════════════════════════════════════════════════════════
    # Complete commands (with new price)
    ("Change burger price to 250", "update_menu_item"),
    ("Update the price of butter chicken to 450", "update_menu_item"),
    ("Set pizza price to 350", "update_menu_item"),
    ("Make dosa price 120", "update_menu_item"),
    ("Change biryani from 300 to 350", "update_menu_item"),
    ("Update samosa price to 40", "update_menu_item"),
    ("Set the cost of paneer tikka to 280", "update_menu_item"),
    ("Increase burger price to 300", "update_menu_item"),
    ("Reduce cold coffee price to 100", "update_menu_item"),
    ("Change naan price to 60", "update_menu_item"),
    ("Update masala dosa to 150 rupees", "update_menu_item"),
    ("Set garlic bread price at 180", "update_menu_item"),
    # Incomplete commands (need follow-up for new price)
    ("Update price of dosa", "update_menu_item"),
    ("Change the price of pizza", "update_menu_item"),
    ("I want to change burger price", "update_menu_item"),
    ("Modify the price of biryani", "update_menu_item"),
    ("Can you update the paneer tikka price?", "update_menu_item"),
    ("I need to change the cost of samosa", "update_menu_item"),
    # Availability toggle
    ("Make pizza unavailable", "update_menu_item"),
    ("Mark samosa as available", "update_menu_item"),
    ("Set burger as out of stock", "update_menu_item"),
    ("Make butter chicken available again", "update_menu_item"),
    ("Disable cold coffee on the menu", "update_menu_item"),
    ("Enable the veg thali item", "update_menu_item"),
    ("Turn off biryani from the menu", "update_menu_item"),
    # Hindi/Hinglish
    ("Burger ki price 250 karo", "update_menu_item"),
    ("Dosa ka price badha do", "update_menu_item"),
    ("Pizza ki price change karo", "update_menu_item"),
    ("Biryani ka rate 350 kar do", "update_menu_item"),
    ("Samosa ka price update karo 50 mein", "update_menu_item"),
    ("Naan ki price kam karo", "update_menu_item"),

    # ═══════════════════════════════════════════════════════════
    # ADD_MENU_ITEM — Add new items to the menu
    # ═══════════════════════════════════════════════════════════
    # Complete commands
    ("Add paneer tikka at 280 in starters", "add_menu_item"),
    ("Add new item chocolate shake for 120", "add_menu_item"),
    ("Create a new dish called veg wrap at 180", "add_menu_item"),
    ("Add mushroom soup to the menu at 150", "add_menu_item"),
    ("Add chicken momos at 200 in appetizers", "add_menu_item"),
    ("Add mango lassi to beverages for 80", "add_menu_item"),
    ("Add a new item: grilled sandwich at 160", "add_menu_item"),
    ("Put garlic fries on the menu for 120", "add_menu_item"),
    ("Add brownie sundae at 220 under desserts", "add_menu_item"),
    ("Add tandoori chicken to main course at 380", "add_menu_item"),
    # Incomplete commands (need follow-up for details)
    ("Add a new item to the menu", "add_menu_item"),
    ("I want to add something to the menu", "add_menu_item"),
    ("Can you add a new dish?", "add_menu_item"),
    ("I need to add a new item", "add_menu_item"),
    ("Add new menu item", "add_menu_item"),
    # Hindi/Hinglish
    ("Naya item daal do menu mein", "add_menu_item"),
    ("Menu mein paneer wrap add karo 220 mein", "add_menu_item"),
    ("Ek naya dish add karna hai", "add_menu_item"),
    ("Chocolate cake daal do 250 mein desserts mein", "add_menu_item"),
    ("Naya item chahiye menu mein", "add_menu_item"),

    # ═══════════════════════════════════════════════════════════
    # DELETE_MENU_ITEM — Remove items from menu
    # ═══════════════════════════════════════════════════════════
    ("Remove cold coffee from the menu", "delete_menu_item"),
    ("Delete the samosa item", "delete_menu_item"),
    ("Take tandoori roti off the menu", "delete_menu_item"),
    ("Remove garlic bread from menu", "delete_menu_item"),
    ("Delete veg thali from the menu", "delete_menu_item"),
    ("I want to remove pasta from the menu", "delete_menu_item"),
    ("Can you delete chocolate shake?", "delete_menu_item"),
    ("Remove mushroom soup", "delete_menu_item"),
    ("Take off the chicken wings from menu", "delete_menu_item"),
    ("Get rid of the old combo meal", "delete_menu_item"),
    ("Drop masala fries from the menu", "delete_menu_item"),
    ("Remove the discontinued items", "delete_menu_item"),
    # Hindi/Hinglish
    ("Hatao garlic bread menu se", "delete_menu_item"),
    ("Cold coffee hata do menu se", "delete_menu_item"),
    ("Menu se samosa nikal do", "delete_menu_item"),
    ("Ye item delete kar do", "delete_menu_item"),
    ("Pasta hata do", "delete_menu_item"),

    # ═══════════════════════════════════════════════════════════
    # MULTI_OPERATION — Multiple operations in a single message
    # ═══════════════════════════════════════════════════════════
    ("Add paneer wrap at 220 in starters and change burger price to 300", "multi_operation"),
    ("Add mango lassi at 120 in beverages and update pizza price to 400", "multi_operation"),
    ("Add spring rolls at 150 and also change biryani price to 350", "multi_operation"),
    ("Add veg burger at 180 and make cold coffee unavailable", "multi_operation"),
    ("Add chocolate shake at 150 and remove garlic bread from menu", "multi_operation"),
    ("Add caesar salad at 180 in starters and delete the old veg thali", "multi_operation"),
    ("Remove samosa and add spring rolls at 150 in appetizers", "multi_operation"),
    ("Change burger price to 300 and remove cold coffee from menu", "multi_operation"),
    ("Update pizza price to 350 and delete the mushroom soup", "multi_operation"),
    ("Make dosa unavailable and change biryani price to 320", "multi_operation"),
    ("Add paneer wrap at 220, change burger to 300, and remove cold coffee", "multi_operation"),
    ("Remove samosa, add spring rolls at 150 in appetizers, and make pizza unavailable", "multi_operation"),
    ("Add mango lassi at 80, update burger price to 280, and remove garlic bread", "multi_operation"),
    ("Change dosa price to 80, add brownie sundae at 200 in desserts, and remove old combo", "multi_operation"),
    ("Add veg wrap at 150, add masala chai at 40, change burger price to 300, and remove cold coffee", "multi_operation"),
    ("Update pizza to 400, remove mushroom soup, add spring rolls at 120, and make dosa unavailable", "multi_operation"),
    ("Burger ki price 300 karo aur cold coffee menu se hatao", "multi_operation"),
    ("Naya item paneer wrap 220 mein add karo aur pizza unavailable kar do", "multi_operation"),
    ("Samosa hatao menu se aur spring rolls 150 mein add karo", "multi_operation"),
    ("Burger ka price 280 karo, dosa ka price 90 karo, aur cold coffee hata do", "multi_operation"),
    ("First add paneer tikka at 280 then change the burger price to 300", "multi_operation"),
    ("Update burger price to 350; also remove the old veg combo", "multi_operation"),
    ("I need to add masala chai at 40 and also remove the garlic bread from menu", "multi_operation"),
    ("Can you add spring rolls at 120 in starters and change dosa price to 100?", "multi_operation"),
    ("Please add a new item veg burger at 180 and remove mushroom soup from menu", "multi_operation"),
    ("Add chocolate lava cake at 200, remove garlic bread, update pizza to 380", "multi_operation"),
    ("Set burger price to 320 and add fresh lime soda at 60 in beverages", "multi_operation"),
    ("Add paneer tikka 280, veg spring rolls 150, and chocolate shake 130 to menu", "multi_operation"),

    # ═══════════════════════════════════════════════════════════
    # GENERATE_REPORT — Generate/download sales reports (daily/weekly/monthly)
    # ═══════════════════════════════════════════════════════════
    ("Generate monthly sales report", "generate_report"),
    ("Create a weekly sales report", "generate_report"),
    ("Give me today's daily report", "generate_report"),
    ("Download the monthly report", "generate_report"),
    ("I need a sales report for this month", "generate_report"),
    ("Generate a report with charts", "generate_report"),
    ("Show me the weekly sales report", "generate_report"),
    ("Prepare the daily sales report", "generate_report"),
    ("Create a downloadable sales report", "generate_report"),
    ("Export monthly sales data as a report", "generate_report"),
    ("Give me a detailed weekly report", "generate_report"),
    ("Generate sales report for last 30 days", "generate_report"),
    ("I want a PDF report of today's sales", "generate_report"),
    ("Monthly report with analytics and charts", "generate_report"),
    ("Sales report download karo", "generate_report"),
    ("Report banao aaj ka", "generate_report"),
    ("Weekly report chahiye", "generate_report"),
    ("Monthly report do", "generate_report"),
    ("Print this month's sales report", "generate_report"),
    ("Generate a quarterly report", "generate_report"),
    ("Can you create a sales report?", "generate_report"),
    ("Download report for last 7 days", "generate_report"),
    ("Sales report with top selling items", "generate_report"),
    ("Give me the full report for this week", "generate_report"),
    ("Generate detailed analytics report", "generate_report"),
    ("Report for last 14 days", "generate_report"),
    ("Please prepare a comprehensive sales report", "generate_report"),
    ("Make a report I can download", "generate_report"),
    ("Daily report generate karo", "generate_report"),
    ("Weekly sales performance report", "generate_report"),
    ("Create monthly performance report", "generate_report"),

    # ═══════════════════════════════════════════════════════════
    # GENERAL — Greetings, capabilities, off-topic
    # ═══════════════════════════════════════════════════════════
    ("Hello", "general"),
    ("Hi there", "general"),
    ("Hey", "general"),
    ("Good morning", "general"),
    ("Good evening", "general"),
    ("What can you do?", "general"),
    ("Help", "general"),
    ("Who are you?", "general"),
    ("What are you?", "general"),
    ("Tell me about yourself", "general"),
    ("What is this system?", "general"),
    ("How do I use this?", "general"),
    ("Thank you", "general"),
    ("Thanks", "general"),
    ("Bye", "general"),
    ("Goodbye", "general"),
    ("See you later", "general"),
    ("What's the weather like?", "general"),
    ("Tell me a joke", "general"),
    ("You're amazing", "general"),
    ("This is great", "general"),
    ("Namaste", "general"),
    ("Kaise ho?", "general"),
    ("Kya kar sakte ho tum?", "general"),
    ("Shukriya", "general"),
    ("Nice", "general"),
    ("Cool", "general"),
    ("Okay", "general"),
    ("Ok thanks", "general"),
    ("Got it", "general"),
]

# ── Semantic Embedding Anchors ──────────────────────────────────
# These are the "gold standard" example sentences per intent.
# The embedding model encodes these, and new queries are matched
# via cosine similarity against these anchors.
INTENT_ANCHORS = {
    "sales_query": [
        "What are today's sales?",
        "How much revenue did we earn?",
        "Total income this week",
        "How many orders today?",
        "Average order value",
        "Peak hours analysis",
        "Sales trend over last 7 days",
        "Compare this week vs last week",
        "Revenue forecast",
        "Best selling day this month",
        "Payment breakdown by mode",
        "Show top 5 selling items",
        "What are the top selling items?",
        "Which items are selling the most?",
        "Top sellers this week",
        "Best selling dishes this month",
    ],
    "inventory_query": [
        "Show me low stock items",
        "Which ingredients are running low?",
        "How much paneer do we have in stock?",
        "What's expiring soon?",
        "Show expired items",
        "Shelf life check",
        "Can we make enough burgers today?",
        "Ingredient availability",
        "Items that need reordering",
        "Stock level report",
    ],
    "order_status": [
        "Show pending orders",
        "What's the status of my order?",
        "Kitchen order status",
        "Orders being prepared right now",
        "Any delayed orders?",
        "KOT status update",
        "Which tables are waiting?",
        "Active orders in the queue",
    ],
    "menu_info": [
        "What's on the menu?",
        "Price of butter chicken",
        "Is pizza available?",
        "Show me all menu items",
        "List items in desserts",
        "How much does a burger cost?",
        "Available dishes right now",
    ],
    "wastage_query": [
        "How much wastage this week?",
        "Spoilage report",
        "Total food waste cost",
        "Which items had the most wastage?",
        "Kitchen waste analysis",
        "Wastage trends over time",
    ],
    "revenue_intel": [
        "What are our profit margins?",
        "Most profitable items",
        "BCG matrix analysis",
        "Suggest combo deals",
        "Upselling suggestions",
        "Price optimization recommendations",
        "Hidden gems on the menu",
        "Low margin high volume risks",
        "Menu engineering report",
        "Contribution margin analysis",
        "Items frequently ordered together",
    ],
    "create_order": [
        "Add 2 burgers to table 5",
        "Place an order for pizza",
        "I want to order butter chicken",
        "Order 3 samosas for takeaway",
        "New order for table 7",
        "Get me 2 coffees",
    ],
    "update_menu_item": [
        "Change burger price to 250",
        "Update the price of butter chicken",
        "Set pizza price to 350",
        "Make dosa price 120",
        "Update price of dosa",
        "Change the price of pizza",
        "Make pizza unavailable",
        "Mark samosa as available",
        "Modify the price of biryani",
        "Set burger as out of stock",
    ],
    "add_menu_item": [
        "Add paneer tikka at 280 in starters",
        "Add new item chocolate shake for 120",
        "Create a new dish called veg wrap",
        "Add a new item to the menu",
        "I want to add something to the menu",
        "Put garlic fries on the menu for 120",
        "Add grilled sandwich at 180, a crispy sandwich, takes 10 minutes",
        "Add masala chai at 40, spiced indian tea, ready in 5 minutes",
    ],
    "delete_menu_item": [
        "Remove cold coffee from the menu",
        "Delete the samosa item",
        "Take tandoori roti off the menu",
        "Remove garlic bread from menu",
        "I want to remove pasta from the menu",
        "Get rid of the old combo meal",
    ],
    "multi_operation": [
        "Add paneer wrap at 220 and change burger price to 300",
        "Remove samosa and add spring rolls at 150",
        "Change burger price to 300 and remove cold coffee",
        "Add paneer wrap at 220, change burger to 300, and remove cold coffee",
        "Update pizza to 400, remove mushroom soup, add spring rolls at 120",
        "Burger ki price 300 karo aur cold coffee menu se hatao",
        "First add paneer tikka at 280 then change the burger price to 300",
    ],
    "generate_report": [
        "Generate monthly sales report",
        "Create a weekly sales report",
        "Give me today's daily report",
        "Download the monthly report",
        "I need a sales report for this month",
        "Generate sales report for last 30 days",
        "Export report with charts",
        "Sales report download",
        "Prepare a comprehensive sales report",
        "Weekly sales performance report",
    ],
    "general": [
        "Hello",
        "What can you do?",
        "Help me",
        "Thank you",
        "Who are you?",
        "Good morning",
        "Tell me a joke",
    ],
}

# Intent descriptions for academic documentation
INTENT_DESCRIPTIONS = {
    "sales_query":       "Revenue, earnings, order counts, AOV, trends, forecasting, payment breakdowns, top sellers",
    "inventory_query":   "Stock levels, ingredient availability, low stock alerts, expiry tracking, reorder needs",
    "order_status":      "Tracking active orders, pending KOTs, kitchen queue, order completion status",
    "menu_info":         "Menu items, prices, availability, categories, dish details",
    "wastage_query":     "Food waste logs, spoilage costs, wastage analysis, waste trends",
    "revenue_intel":     "Profit margins, BCG classification, combo recommendations, upselling, pricing optimization",
    "create_order":      "Placing new orders, adding items to orders, specifying table and order type",
    "update_menu_item":  "Changing menu item prices, toggling availability, updating item details in real-time",
    "add_menu_item":     "Adding new dishes/items to the restaurant menu with name, price, category, description, and prep time",
    "delete_menu_item":  "Removing or disabling items from the restaurant menu",
    "multi_operation":   "Combined intents containing multiple commands in a single message (e.g., 'Add X, change Y, remove Z')",
    "generate_report":   "Generating comprehensive sales reports (daily/weekly/monthly) with charts, KPIs, and downloadable PDF",
    "general":           "Greetings, help requests, capabilities inquiry, off-topic, pleasantries",
}
